domains:
  - domain: "www.google.com"
    port: 443
    displayName: "Google"

  - domain: "www.ebay.com"
    port: 443
    displayName: "eBay"

  - domain: "www.amazon.com"
    port: 443
    displayName: "amazon"

  - domain: "www.facebook.com"
    port: 443
    displayName: "facebook"

# Point to .sh for unix based and .bat for windows
cmdFile: "monitors/SslCertificateMonitor/cmd/openssl.sh"
metricPrefix:  "Custom Metrics|SslCertificate|"

# number of concurrent tasks
numberOfThreads: 10

#timeout for the thread
threadTimeout: 30