### ANY CHANGES TO THIS FILE DOES NOT REQUIRE A RESTART ###

#This will create this metric in all the tiers, under this path
#metricPrefix:  "Custom Metrics|SslCertificate"

#This will create it in specific Tier. Replace <TIER_ID>
metricPrefix: Server|Component:<TIER NAME OR TIER ID>|Custom Metrics|SslCertificate

enableHealthChecks: false

domains:
  - domain: "www.google.com"
    port: 443
    displayName: "Google"

  - domain: "www.ebay.com"
    port: 443
    displayName: "eBay"

  - domain: "www.amazon.com"
    port: 443
    displayName: "amazon"

#### Configurations below this need not be changed.###
# number of concurrent tasks
numberOfThreads: 10

#timeout for the thread
threadTimeout: 5
