domains:
  - domain: "www.google.com"
    port: 443
    displayName: "Google"

  - domain: "www.ebay.com"
    port: 443
    displayName: "eBay"



cmdFile: "monitors/SslCertificateMonitor/cmd/openssl.sh"
metricPrefix:  "Custom Metrics|SslCertificate|"